removed syntax error

diff --git a/.github/workflows/validate-xml.yml b/.github/workflows/validate-xml.yml
--- a/.github/workflows/validate-xml.yml
+++ b/.github/workflows/validate-xml.yml
@@ -66,10 +66,10 @@ jobs:
           path: .github/workflow-reports/mei-dc-validation_report.md
 
       - name: Commit and Push Report (Optional)
-          run: |
-            git config --local user.email "action@github.com"
-            git config --local user.name "GitHub Action"
-            git add .github/workflow-reports/mei-dc-validation_report.md
-            git commit -m "Update XML validation report" || echo "No changes to commit"
-            git push
-            # Note: The 'git push' step will fail in Pull Request workflows unless you use a specific token
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .github/workflow-reports/mei-dc-validation_report.md
+          git commit -m "Update XML validation report" || echo "No changes to commit"
+          git push
+          # Note: The 'git push' step will fail in Pull Request workflows unless you use a specific token
